---
title: "2nd_stats"
author: "郑元瑞"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
knitr::opts_chunk$set(echo = FALSE, eval = FALSE, message = FALSE, cache = TRUE)
library(here)
library(tidyverse)
library(MKinfer)#for permutation t test
installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
version
options(mc.cores = parallel::detectCores())
options(scipen = 9)
here::here()
```

```{r}
c_con1 <- readr::read_csv(here("2_Data", "result1_cross_con.csv"))
c_con2 <- readr::read_csv(here("2_Data", "result2_cross_con.csv"))
c_exp <- readr::read_csv(here("2_Data", "Cross_Exp.csv"))
c_con1_tb <- readr::read_csv(here("2_Data", "result1_cross_con_tb.csv"))
c_con2_tb <- readr::read_csv(here("2_Data", "result2_cross_con_tb.csv"))
c_exp_tb <- readr::read_csv(here("2_Data", "Cross_Exp_tb.csv"))
```
```{r}
avg_fold_c1 <- c_con1 %>%
  dplyr::group_by(sub, source, target) %>%
  dplyr::summarise(m_score = mean(score)) %>%
  ungroup()

avg_fold_c2 <- c_con2 %>%
  dplyr::group_by(sub, source, target) %>%
  dplyr::summarise(m_score = mean(score)) %>%
  ungroup()

avg_fold_cexp2 <- c_exp %>%
  dplyr::group_by(sub, source, target, experiment) %>%
  dplyr::summarise(m_score = mean(score)) %>%
  ungroup()

avg_fold_c1tb <- c_con1_tb %>%
  dplyr::group_by(sub, source, target) %>%
  dplyr::summarise(m_score = mean(score)) %>%
  ungroup()

avg_fold_c2tb <- c_con2_tb %>%
  dplyr::group_by(sub, source, target) %>%
  dplyr::summarise(m_score = mean(score)) %>%
  ungroup()

avg_fold_cexp2tb <- c_exp_tb %>%
  dplyr::group_by(sub, source, target, experiment) %>%
  dplyr::summarise(m_score = mean(score)) %>%
  ungroup()
```

```{r}
nest_st1 <- avg_fold_c1 %>%
  dplyr::group_nest(source, target)

nest_st2 <- avg_fold_c2 %>%
  dplyr::group_nest(source, target)

nest_stexp <- avg_fold_cexp2 %>%
  dplyr::group_nest(source, target, experiment)

nest_st1tb <- avg_fold_c1tb %>%
  dplyr::group_nest(source, target)

nest_st2tb <- avg_fold_c2tb %>%
  dplyr::group_nest(source, target)

nest_stexptb <- avg_fold_cexp2tb %>%
  dplyr::group_nest(source, target, experiment)

result1 <- nest_st1 %>%
  dplyr::mutate(
    model = purrr::map(
      data,
      ~ perm.t.test(.x$m_score,
       alternative = "greater",
       mu = 0.5, paired = FALSE,
       conf.level = 0.95, R = 10000)
    ),
    p_val = purrr::map_dbl(model, ~ .x$p.value*40),
    mean = purrr::map_dbl(data, ~ mean(.x$m_score)),
    sd = purrr::map_dbl(data, ~ sd(.x$m_score))
  )

result2 <- nest_st2 %>%
  dplyr::mutate(
    model = purrr::map(
      data,
      ~ perm.t.test(.x$m_score,
       alternative = "greater",
       mu = 0.5, paired = FALSE,
       conf.level = 0.95, R = 10000)
    ),
    p_val = purrr::map_dbl(model, ~ .x$p.value*40),
    mean = purrr::map_dbl(data, ~ mean(.x$m_score)),
    sd = purrr::map_dbl(data, ~ sd(.x$m_score))
  )

result3 <- nest_stexp %>%
  dplyr::mutate(
    model = purrr::map(
      data,
      ~ perm.t.test(.x$m_score,
       alternative = "greater",
       mu = 0.5, paired = FALSE,
       conf.level = 0.95, R = 10000)
    ),
    p_val = purrr::map_dbl(model, ~ .x$p.value*40),
    mean = purrr::map_dbl(data, ~ mean(.x$m_score)),
    sd = purrr::map_dbl(data, ~ sd(.x$m_score))
  )

result1tb <- nest_st1tb %>%
  dplyr::mutate(
    model = purrr::map(
      data,
      ~ perm.t.test(.x$m_score,
       alternative = "greater",
       mu = 0.5, paired = FALSE,
       conf.level = 0.95, R = 10000)
    ),
    p_val = purrr::map_dbl(model, ~ .x$p.value*40),
    mean = purrr::map_dbl(data, ~ mean(.x$m_score)),
    sd = purrr::map_dbl(data, ~ sd(.x$m_score))
  )

result2tb <- nest_st2tb %>%
  dplyr::mutate(
    model = purrr::map(
      data,
      ~ perm.t.test(.x$m_score,
       alternative = "greater",
       mu = 0.5, paired = FALSE,
       conf.level = 0.95, R = 10000)
    ),
    p_val = purrr::map_dbl(model, ~ .x$p.value*40),
    mean = purrr::map_dbl(data, ~ mean(.x$m_score)),
    sd = purrr::map_dbl(data, ~ sd(.x$m_score))
  )

result3tb <- nest_stexptb %>%
  dplyr::mutate(
    model = purrr::map(
      data,
      ~ perm.t.test(.x$m_score,
       alternative = "greater",
       mu = 0.5, paired = FALSE,
       conf.level = 0.95, R = 10000)
    ),
    p_val = purrr::map_dbl(model, ~ .x$p.value*40),
    mean = purrr::map_dbl(data, ~ mean(.x$m_score)),
    sd = purrr::map_dbl(data, ~ sd(.x$m_score))
  )
```

```{r}
result1
```

```{r}
result2
```
```{r}
result3
```



```{r}
result1 <- result1 %>%
  dplyr::mutate(experiment = "exp1")
result2 <- result2 %>%
  dplyr::mutate(experiment = "exp2")

result1tb <- result1tb %>%
  dplyr::mutate(experiment = "exp1")
result2tb <- result2tb %>%
  dplyr::mutate(experiment = "exp2")
```

```{r}
dat1 <- result1 %>%
  dplyr::select(source, target, experiment, mean, sd, p_val)

dat2 <- result2 %>%
  dplyr::select(source, target, experiment, mean, sd, p_val)

dat3 <- result3 %>%
  dplyr::select(source, target, experiment, mean, sd, p_val)
result_all <- rbind(dat1, dat2, dat3)
result_all <- result_all %>%
  dplyr::rename(
    mean_roc_auc_score = mean,
    p_value = p_val
  ) %>%
  dplyr::mutate(sig = case_when(
    p_value < 0.01 ~ "<0.01",
    .default = as.character(p_value)
  ))
result_all <- result_all %>% 
  tidyr::unite("mean +/- std", mean_roc_auc_score:sd, sep="+/-")

dat1tb <- result1tb %>%
  dplyr::select(source, target, experiment, mean, sd, p_val)

dat2tb <- result2tb %>%
  dplyr::select(source, target, experiment, mean, sd, p_val)

dat3tb <- result3tb %>%
  dplyr::select(source, target, experiment, mean, sd, p_val)
result_alltb <- rbind(dat1tb, dat2tb, dat3tb)
result_alltb <- result_alltb %>%
  dplyr::rename(
    mean_roc_auc_score = mean,
    p_value = p_val
  ) %>%
  dplyr::mutate(sig = case_when(
    p_value < 0.01 ~ "<0.01",
    .default = as.character(p_value)
  ))
result_alltb <- result_alltb %>% 
  tidyr::unite("mean +/- std", mean_roc_auc_score:sd, sep="+/-")
write_csv(result_all, paste(here("2_Data"), "permutation_result.csv", sep = "/"))
write_csv(result_alltb, paste(here("2_Data"), "permutation_result_tb.csv", sep = "/"))
```



